spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure=ERROR: